name: cereal linux ci
on: [push, pull_request]

jobs:
  test_cereal_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON -DSKIP_PERFORMANCE_COMPARISON=ON'
            COMPILER: 'g++-13'
            EXTRA_APT_PACKAGES: 'g++-13'
            CONTAINER: ubuntu:24.04
            NAME: ubuntu-24.04-g++13

          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON -DSKIP_PERFORMANCE_COMPARISON=ON'
            COMPILER: 'g++-13'
            EXTRA_APT_PACKAGES: 'g++-13'
            CONTAINER: ubuntu:24.04
            NAME: ubuntu-24.04-g++13

          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON -DSKIP_PERFORMANCE_COMPARISON=ON'
            COMPILER: 'g++-13'
            EXTRA_APT_PACKAGES: 'g++-13'
            CONTAINER: ubuntu:24.04
            NAME: ubuntu-24.04-g++13

          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON'
            COMPILER: 'g++-13'
            EXTRA_APT_PACKAGES: 'g++-13'
            CONTAINER: ubuntu:24.04
            NAME: ubuntu-24.04-g++13

          - COMPILER: 'g++-14'
            EXTRA_APT_PACKAGES: 'gcc-multilib g++-14-multilib linux-libc-dev'
            CONTAINER: ubuntu:24.04
            NAME: ubuntu-24.04-g++14-multilib

          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON'
            COMPILER: 'g++-14'
            EXTRA_APT_PACKAGES: 'g++-14'
            CONTAINER: ubuntu:24.04
            NAME: ubuntu-24.04-g++14

          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON -DCMAKE_CXX_STANDARD=17'
            COMPILER: 'g++-14'
            EXTRA_APT_PACKAGES: 'g++-14'
            CONTAINER: ubuntu:24.04
            NAME: ubuntu-24.04-g++14

          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON -DCMAKE_CXX_STANDARD=17'
            COMPILER: 'g++-12'
            EXTRA_APT_PACKAGES: 'g++-12'
            CONTAINER: ubuntu:22.04
            NAME: ubuntu-22.04-g++12
          
          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON -DCMAKE_CXX_STANDARD=17'
            COMPILER: 'g++-9'
            EXTRA_APT_PACKAGES: 'g++-9'
            CONTAINER: ubuntu:20.04
            NAME: ubuntu-20.04-g++9
          
          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON -DCMAKE_CXX_STANDARD=17'
            COMPILER: 'g++-10'
            EXTRA_APT_PACKAGES: 'g++-10'
            CONTAINER: ubuntu:20.04
            NAME: ubuntu-20.04-g++10
          
          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON -DCMAKE_CXX_STANDARD=17'
            COMPILER: 'clang++-9'
            EXTRA_APT_PACKAGES: 'clang-9'
            CONTAINER: ubuntu:20.04
            NAME: ubuntu-20.04-clang-9-cpp17
          
          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON -DCMAKE_CXX_STANDARD=17'
            COMPILER: 'clang++-10'
            EXTRA_APT_PACKAGES: 'clang-10'
            CONTAINER: ubuntu:20.04
            NAME: ubuntu-20.04-clang-10-cpp17
          
          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON -DCMAKE_CXX_STANDARD=17'
            COMPILER: 'clang++-11'
            EXTRA_APT_PACKAGES: 'clang-11'
            CONTAINER: ubuntu:20.04
            NAME: ubuntu-20.04-clang-11-cpp17
          
          - CMAKE_OPTIONS: '-DSKIP_PORTABILITY_TEST=ON -DCMAKE_CXX_STANDARD=17'
            COMPILER: 'clang++-12'
            EXTRA_APT_PACKAGES: 'clang-12'
            CONTAINER: ubuntu:20.04
            NAME: ubuntu-20.04-clang-12-cpp17
    name: ${{ matrix.name }}

    steps:
    - name: Check out the repo
      uses: actions/checkout@v7
    - name: install deps and test
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ matrix.CONTAINER }}
        options: -v ${{ github.workspace }}:/var/workspace 
        shell: bash
        run: |
          set -ex
          apt-get update -y
          DEBIAN_FRONTEND=noninteractive TZ=America/Los_Angeles apt-get install -y software-properties-common wget python3-pip make apt-transport-https

          # Add apt repositories for older Ubuntu
          . /etc/os-release

          if [[ "${{ matrix.LLVM_APT_SOURCE }}" != "" ]]; then
            wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
            add-apt-repository "${{ matrix.LLVM_APT_SOURCE }}"
          fi

          apt-get update -y

          # Install apt packages
          apt-get install libboost-serialization-dev libboost-dev ${{ matrix.EXTRA_APT_PACKAGES }} -y
          pip3 install --upgrade "pip"
          pip3 install cmake

          # Set compiler and env variables
          cd /var/workspace
          export CXX=${{ matrix.COMPILER }}
          ${CXX} --version
          DEPS_DIR="${PWD}/deps"
          mkdir -p "${DEPS_DIR}"
          pushd "${DEPS_DIR}"
          JOBS=2

          # Install the right version of libc++
          LLVM_INSTALL=${DEPS_DIR}/llvm/install
          # if in linux and compiler clang and llvm not installed
          if [[ "${CXX}" == "clang"* && -n "$(ls -A ${LLVM_INSTALL})" ]]; then
            LLVM_URL="http://llvm.org/releases/${LLVM_VERSION}/llvm-${LLVM_VERSION}.src.tar.xz"
            LIBCXX_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxx-${LLVM_VERSION}.src.tar.xz"
            LIBCXXABI_URL="http://llvm.org/releases/${LLVM_VERSION}/libcxxabi-${LLVM_VERSION}.src.tar.xz"
            mkdir -p llvm llvm/build llvm/projects/libcxx llvm/projects/libcxxabi
            wget -O - ${LLVM_URL} | tar --strip-components=1 -xJ -C llvm
            wget -O - ${LIBCXX_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxx
            wget -O - ${LIBCXXABI_URL} | tar --strip-components=1 -xJ -C llvm/projects/libcxxabi
            (cd llvm/build && cmake .. -DCMAKE_INSTALL_PREFIX=${LLVM_INSTALL})
            (cd llvm/build/projects/libcxx && make install -j2)
            (cd llvm/build/projects/libcxxabi && make install -j2)
            export CXXFLAGS="-isystem ${LLVM_INSTALL}/include/c++/v1"
            export LDFLAGS="-L ${LLVM_INSTALL}/lib -l c++ -l c++abi"
            export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${LLVM_INSTALL}/lib"
          fi

          popd

          # Build cereal and test
          cmake --version
          mkdir build && cd build
          cmake ${{ matrix.CMAKE_OPTIONS }} .. && make -j4 VERBOSE=1
          ctest . --output-on-failure
